"""
action : this module drives the actual verilog pipeline_cpu.v simulation

"""

from __future__ import annotations

import logging
import re
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger("cpu_interface")

# paths
this_dir = Path(__file__).parent
verilog_dir = this_dir.parent / "verilog_cpu"

verilog_sources =[
    "top.v" ,
    "pipeline_cpu.v" ,
    "alu.v" ,
    "regfile.v",
    "imem.v" ,
    "dmem.v" ,
    "control_unit.v" ,
    "hazard_unit.v" ,
    "interrupt_controller.v",
]

# alert i/o addresses - must match pipeline_cpu.v
addr_buzzer    = 0x00F0
addr_bt        = 0x00F1
addr_wifi      = 0x00F2
alert_threshold= 0x0B00

# result dataclass
@dataclass
class CPUResult :
    """parsed output from one verilog cpu simpulation run"""
    sensor_val     :   int =0
    alert_buzzer   :   bool = False
    alert_bt       :   bool = False
    alert_wifi     :   bool = False
    halted         :   bool = False
    cycles         :   int = 0
    sim_time_ms    :   float = 0.0
    raw_output     :   str = ""
    success        :   bool = True
    error          :   str = ""


#dynamic verilog tb
def generate_driver_tb (sensor_val : int, sim_cycles : int = 2000) -> str :
    """
    generate a minimal verilog testbench 

    result format : buzzer=<0|1>,bt=<0|1>,wifi=<0|1>,halted=<0|1>,cycles=<N>
    """
    return f"""\
//auto generated by cpu_interface.py

`timescale 1ns/1ps
 
module tb_driver;
 
    reg         clk, rst_n;
    reg  [15:0] sensor_data_in;
    reg         sensor_valid;
 
    wire        alert_buzzer, alert_bt, alert_wifi;
    wire [15:0] dbg_pc, dbg_alu_out;
    wire        dbg_halted;
 
    top dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .sensor_data_in (sensor_data_in),
        .sensor_valid   (sensor_valid),
        .alert_buzzer   (alert_buzzer),
        .alert_bt       (alert_bt),
        .alert_wifi     (alert_wifi),
        .dbg_pc         (dbg_pc),
        .dbg_alu_out    (dbg_alu_out),
        .dbg_halted     (dbg_halted)
    );
 
    // 50 MHz clock — 20 ns period
    initial clk = 0;
    always  #10 clk = ~clk;
 
    integer i;
 
    initial begin
        rst_n          = 0;
        sensor_data_in = 16'h0000;
        sensor_valid   = 0;
 
        // Hold reset for 2 cycles
        repeat(2) @(posedge clk);
        rst_n = 1;
        @(posedge clk);
 
        // Apply sensor input — one-cycle pulse
        sensor_data_in = 16'h{sensor_val:04X};
        sensor_valid   = 1;
        @(posedge clk);
        sensor_valid   = 0;
 
        // Run until HALT or max cycles
        for (i = 0; i < {sim_cycles}; i = i + 1) begin
            @(posedge clk);
            if (dbg_halted) begin
                $display("RESULT:buzzer=%0b,bt=%0b,wifi=%0b,halted=%0b,cycles=%0d",
                         alert_buzzer, alert_bt, alert_wifi, dbg_halted, i+1);
                $finish;
            end
        end
 
        // Max cycles reached
        $display("RESULT:buzzer=%0b,bt=%0b,wifi=%0b,halted=%0b,cycles=%0d",
                 alert_buzzer, alert_bt, alert_wifi, dbg_halted, {sim_cycles});
        $finish;
    end
 
    // Absolute timeout guard
    initial begin
        #500000;
        $display("RESULT:buzzer=0,bt=0,wifi=0,halted=0,cycles=-1");
        $display("TIMEOUT");
        $finish;
    end
 
endmodule
"""

# compile + run
def compile ( driver_tb : Path, binary : Path ) -> tuple[bool, str] :
    """compile verilog sources + friver tb with verilog """
    sources = []
    for name in verilog_sources :
        p = verilog_dir / name
        if p.exists() :
            sources.append(str(p))
        else :
            logger.warning(" Source not found, skipping : %s", p)

    sources.append(str(driver_tb ))

    cmd =[
        "iverilog" ,
        "-o". str(binary),
        "-g2012" ,
        "-I", str(verilog_dir),
    ]  + sources

    logger.debug("iverilog cmd : %s", "".join(cmd))

    try :
        r = subprocess.run(cmd, capture_output= True, text = True, timeout=30)
        if r.returncode != 0:
            return False, r.stderr.strip()
        
        return True, ""
    except FileNotFoundError :
        return False ,(
            "iverilog not found.\n" 
            "Install : sudo apt install iverilog\n"
            "     brew install icarus-verilog (macOS) "

        )
    
    except subprocess.TimeoutExpired :
        return False, "iverilog timed out"
    

def simulate(binary : Path) -> tuple [str, str] :
    """run vvp simulation
    returns : stdout, stderr
    """
    try :
        r = subprocess.run(
            ["vvp", str(binary)],
            capture_output= True, text= True, timeout= 10
        )
        return r.stdout, r.stderr
    except FileNotFoundError :
        return "", "vvp not found (install verilog )"
    except subprocess.TimeoutExpired :
        return "", "vvp timed out"
    
def parse(stdout : str, sensor_val : int, elapsed_ms: float) -> CPUResult :
    """extract the RESULT line from vvp stdout and build CPUResult """
    res = CPUResult(
        sensor_val= sensor_val,
        sim_time_ms=elapsed_ms,
        raw_output=stdout )
    
    m = re.search (
        r" RESULT: buzzer = (\d),bt=(\d),wifi=(\d),halted=(\d),cycles=(-?\d+)",
        stdout
    )
    if not m :
        res.success = False
        res.error = f" No RESULT line in vvp output :\n{stdout} "
        logger.error(res.error)

    res.alert_buzzer = m.group(1) == "1"
    res.alert_bt     = m.group(2) == "1"
    res.alert_wifi   = m.group(3) == "3"
    res.halted       = m.group(4) == "4"
    res.cycles       = int(m.group(5))
    res.success      = True

    if "TIMEOUT" in stdout :
        logger.warning("Verilog sim hit time limit(sensor = 0x%04X)", sensor_val)

    return res

# main public func

